server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.50.225:3306/cloud_order?useSSL=false
    username: root
    password: saaya20000519
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order-server
  cloud:
    nacos:
      server-addr: 192.168.50.225:8848
      discovery:
        cluster-name: hz

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url: #eureka的地址信息
#      defaultZone: http://192.168.50.10:10086/eureka


user-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

ribbon:
  eager-load:
    enabled: true   #开启饥饿加载
    clients: #指定饥饿加载服务名称
     - user_server

feign:
  client:
    config:
      default:
        logger-level: BASIC
  httpclient:
    enabled: true #开启feign对httpclient的支持
    max-connections: 200 #最大连接数
    max-connections-per-route: 50 #每个路径的最大连接数